import = ["/home/Ryan/.config/alacritty/onenord.toml"]
live_config_reload = true

[window]
decorations = "none"
opacity = 0.99
#size = 13.0

[window.dimensions]
columns = 100
lines = 100

[window.padding]
x = 10
y = 10
